apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-web-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/lostinthekernel/deployment-practice.git  # 🔥 replace this
    targetRevision: HEAD
    path: helm/go-web-app-chart

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true        # removes old resources
      selfHeal: true     # auto-fixes drift

    syncOptions:
      - CreateNamespace=true